apiVersion: v1
kind: Pod
metadata:
  name: lifedemop
spec:
  containers:
  - name: lifedemo
    image: i2b2/i2b2-pg:0.5
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "sleep 10;echo Hello from the postStart handler > /cache/message; sh update_pm_cell_data.sh >> /cache/message; "]
  volumes:
  - name: cache-volume
    emptyDir: {}
  restartPolicy: Never
